// vault-sdk-svelte/src/lib/components/SignUp.svelte
<script lang="ts">
  /**
   * SignUp Component
   * 
   * A complete sign-up form with email/password and OAuth support.
   * 
   * @example
   * ```svelte
   * <SignUp 
   *   redirectUrl="/dashboard"
   *   oauthProviders={['google', 'github']}
   * />
   * ```
   */
  import { useSignUp } from '../stores/auth.js';
  import type { SignUpProps, ApiError } from '../types.js';
  
  let { 
    redirectUrl,
    onSignUp,
    onError,
    oauthProviders = [],
    requireName = false,
    className = ''
  }: SignUpProps = $props();
  
  // Form state
  let email = $state('');
  let password = $state('');
  let name = $state('');
  
  // Use sign up hook
  const { signUp, signUpWithOAuth, isLoading, error, resetError } = useSignUp();
  
  // Handle email/password sign up
  async function handleSubmit(e: Event) {
    e.preventDefault();
    resetError();
    
    try {
      await signUp({ 
        email, 
        password,
        ...(name && { name })
      });
      onSignUp?.();
    } catch (e) {
      onError?.(e as ApiError);
    }
  }
  
  // Handle OAuth sign up
  async function handleOAuth(provider: string) {
    resetError();
    
    try {
      await signUpWithOAuth({ provider, redirectUrl });
    } catch (e) {
      onError?.(e as ApiError);
    }
  }
</script>

<div class="vault-signup {className}">
  {#if oauthProviders.length > 0}
    <div class="vault-oauth-buttons">
      {#each oauthProviders as provider}
        <button
          type="button"
          class="vault-btn vault-btn-oauth vault-btn-{provider}"
          onclick={() => handleOAuth(provider)}
          disabled={isLoading}
        >
          {#if provider === 'google'}
            <svg viewBox="0 0 24 24" class="vault-icon"><path fill="currentColor" d="M22.56 12.25c0-.78-.07-1.53-.2-2.25H12v4.26h5.92c-.26 1.37-1.04 2.53-2.21 3.31v2.77h3.57c2.08-1.92 3.28-4.74 3.28-8.09z"/><path fill="currentColor" d="M12 23c2.97 0 5.46-.98 7.28-2.66l-3.57-2.77c-.98.66-2.23 1.06-3.71 1.06-2.86 0-5.29-1.93-6.16-4.53H2.18v2.84C3.99 20.53 7.7 23 12 23z"/><path fill="currentColor" d="M5.84 14.09c-.22-.66-.35-1.36-.35-2.09s.13-1.43.35-2.09V7.07H2.18C1.43 8.55 1 10.22 1 12s.43 3.45 1.18 4.93l2.85-2.22.81-.62z"/><path fill="currentColor" d="M12 5.38c1.62 0 3.06.56 4.21 1.64l3.15-3.15C17.45 2.09 14.97 1 12 1 7.7 1 3.99 3.47 2.18 7.07l3.66 2.84c.87-2.6 3.3-4.53 6.16-4.53z"/></svg>
            Continue with Google
          {:else if provider === 'github'}
            <svg viewBox="0 0 24 24" class="vault-icon"><path fill="currentColor" d="M12 1C5.92 1 1 5.92 1 12c0 4.87 3.15 8.99 7.52 10.44.55.1.75-.24.75-.53 0-.26-.01-.96-.01-1.88-3.06.66-3.71-1.48-3.71-1.48-.5-1.27-1.22-1.61-1.22-1.61-1-.68.08-.66.08-.66 1.1.08 1.68 1.13 1.68 1.13.98 1.68 2.57 1.2 3.2.91.1-.71.38-1.2.7-1.47-2.44-.28-5.01-1.22-5.01-5.44 0-1.2.43-2.19 1.13-2.96-.11-.28-.49-1.39.11-2.9 0 0 .92-.29 3.02 1.13.88-.25 1.82-.37 2.76-.37.93 0 1.88.13 2.76.37 2.09-1.42 3.01-1.13 3.01-1.13.6 1.51.22 2.62.11 2.9.71.77 1.13 1.76 1.13 2.96 0 4.23-2.57 5.16-5.02 5.42.4.34.75 1.01.75 2.04 0 1.47-.01 2.66-.01 3.02 0 .29.2.64.76.53C19.86 20.99 23 16.87 23 12c0-6.08-4.92-11-11-11z"/></svg>
            Continue with GitHub
          {:else if provider === 'microsoft'}
            <svg viewBox="0 0 21 21" class="vault-icon"><path fill="currentColor" d="M1 1h9v9H1V1zm10 0h9v9h-9V1zM1 11h9v9H1v-9zm10 0h9v9h-9v-9z"/></svg>
            Continue with Microsoft
          {:else}
            Continue with {provider}
          {/if}
        </button>
      {/each}
    </div>
    
    <div class="vault-divider">
      <span>or</span>
    </div>
  {/if}
  
  <form onsubmit={handleSubmit} class="vault-form">
    {#if requireName}
      <div class="vault-form-group">
        <label for="name" class="vault-label">Full name</label>
        <input
          id="name"
          type="text"
          bind:value={name}
          placeholder="John Doe"
          required={requireName}
          disabled={isLoading}
          class="vault-input"
        />
      </div>
    {/if}
    
    <div class="vault-form-group">
      <label for="email" class="vault-label">Email</label>
      <input
        id="email"
        type="email"
        bind:value={email}
        placeholder="name@example.com"
        required
        disabled={isLoading}
        class="vault-input"
      />
    </div>
    
    <div class="vault-form-group">
      <label for="password" class="vault-label">Password</label>
      <input
        id="password"
        type="password"
        bind:value={password}
        placeholder="Create a password"
        required
        minlength={8}
        disabled={isLoading}
        class="vault-input"
      />
      <p class="vault-hint">Must be at least 8 characters</p>
    </div>
    
    {#if error}
      <div class="vault-error" role="alert">
        {error.message}
      </div>
    {/if}
    
    <button
      type="submit"
      disabled={isLoading}
      class="vault-btn vault-btn-primary"
    >
      {#if isLoading}
        Creating account...
      {:else}
        Sign up
      {/if}
    </button>
  </form>
  
  <div class="vault-footer">
    <p>
      Already have an account?
      <a href="/sign-in" class="vault-link">Sign in</a>
    </p>
  </div>
</div>

<style>
  .vault-signup {
    max-width: 400px;
    margin: 0 auto;
    padding: 1.5rem;
    font-family: system-ui, -apple-system, sans-serif;
  }
  
  .vault-oauth-buttons {
    display: flex;
    flex-direction: column;
    gap: 0.75rem;
    margin-bottom: 1.5rem;
  }
  
  .vault-btn {
    display: flex;
    align-items: center;
    justify-content: center;
    gap: 0.5rem;
    padding: 0.625rem 1rem;
    border-radius: 0.375rem;
    font-size: 0.875rem;
    font-weight: 500;
    cursor: pointer;
    transition: all 0.15s;
  }
  
  .vault-btn:disabled {
    opacity: 0.5;
    cursor: not-allowed;
  }
  
  .vault-btn-oauth {
    background: white;
    border: 1px solid #e5e7eb;
    color: #374151;
  }
  
  .vault-btn-oauth:hover:not(:disabled) {
    background: #f9fafb;
  }
  
  .vault-btn-primary {
    width: 100%;
    background: #111827;
    border: none;
    color: white;
  }
  
  .vault-btn-primary:hover:not(:disabled) {
    background: #1f2937;
  }
  
  .vault-icon {
    width: 1.25rem;
    height: 1.25rem;
  }
  
  .vault-divider {
    display: flex;
    align-items: center;
    margin: 1.5rem 0;
    color: #6b7280;
    font-size: 0.875rem;
  }
  
  .vault-divider::before,
  .vault-divider::after {
    content: '';
    flex: 1;
    height: 1px;
    background: #e5e7eb;
  }
  
  .vault-divider span {
    padding: 0 1rem;
  }
  
  .vault-form {
    display: flex;
    flex-direction: column;
    gap: 1rem;
  }
  
  .vault-form-group {
    display: flex;
    flex-direction: column;
    gap: 0.25rem;
  }
  
  .vault-label {
    font-size: 0.875rem;
    font-weight: 500;
    color: #374151;
  }
  
  .vault-input {
    padding: 0.5rem 0.75rem;
    border: 1px solid #d1d5db;
    border-radius: 0.375rem;
    font-size: 0.875rem;
    transition: border-color 0.15s;
  }
  
  .vault-input:focus {
    outline: none;
    border-color: #3b82f6;
    ring: 2px solid #bfdbfe;
  }
  
  .vault-input:disabled {
    background: #f3f4f6;
    cursor: not-allowed;
  }
  
  .vault-hint {
    font-size: 0.75rem;
    color: #6b7280;
    margin: 0;
  }
  
  .vault-error {
    padding: 0.75rem;
    background: #fef2f2;
    border: 1px solid #fecaca;
    border-radius: 0.375rem;
    color: #dc2626;
    font-size: 0.875rem;
  }
  
  .vault-footer {
    margin-top: 1.5rem;
    padding-top: 1.5rem;
    border-top: 1px solid #e5e7eb;
    text-align: center;
    font-size: 0.875rem;
    color: #6b7280;
  }
  
  .vault-link {
    color: #3b82f6;
    text-decoration: none;
    font-weight: 500;
  }
  
  .vault-link:hover {
    text-decoration: underline;
  }
</style>

// fantasticauth-sdk-vue/src/components/SignUp.vue
<template>
  <div class="vault-sign-up" :class="props.class">
    <div class="vault-card vault-card-centered">
      <div class="vault-card-header">
        <h2 class="vault-title">Create Account</h2>
      </div>

      <div class="vault-card-content">
        <div v-if="displayError" class="vault-alert vault-alert-error" style="margin-bottom: 1rem;">
          {{ displayError }}
        </div>

        <div v-if="socialButtonsPlacement === 'top' && hasOAuthProviders" class="vault-social-section">
          <slot name="oauth-buttons" :providers="oauthProviders" :handle-o-auth="handleOAuth">
            <div class="vault-social-buttons">
              <button
                v-for="provider in oauthProviders"
                :key="provider"
                type="button"
                class="vault-btn vault-btn-social"
                :disabled="isLoading"
                @click="handleOAuth(provider)"
              >
                <span class="vault-social-icon">{{ getProviderIcon(provider) }}</span>
                <span>Continue with {{ capitalize(provider) }}</span>
              </button>
            </div>
            <div class="vault-divider">
              <span class="vault-divider-text">or</span>
            </div>
          </slot>
        </div>

        <form @submit.prevent="handleSubmit">
          <div v-if="requireName" class="vault-form-group">
            <label class="vault-label" for="vault-name">Full Name</label>
            <input
              id="vault-name"
              v-model="name"
              type="text"
              class="vault-input"
              placeholder="John Doe"
              required
              autocomplete="name"
              :disabled="isLoading"
            />
          </div>

          <div class="vault-form-group">
            <label class="vault-label" for="vault-email">Email</label>
            <input
              id="vault-email"
              v-model="email"
              type="email"
              class="vault-input"
              placeholder="you@example.com"
              required
              autocomplete="email"
              :disabled="isLoading"
            />
          </div>

          <div class="vault-form-group">
            <label class="vault-label" for="vault-password">Password</label>
            <input
              id="vault-password"
              v-model="password"
              type="password"
              class="vault-input"
              placeholder="••••••••"
              required
              autocomplete="new-password"
              :disabled="isLoading"
              minlength="8"
            />
            <small class="vault-hint">Must be at least 8 characters</small>
          </div>

          <button
            type="submit"
            class="vault-btn vault-btn-primary vault-btn-full"
            style="margin-top: 0.5rem;"
            :disabled="isLoading || !isValid"
          >
            <span v-if="isLoading" class="vault-spinner vault-spinner-small vault-spinner-inline"></span>
            {{ isLoading ? 'Creating account...' : 'Create Account' }}
          </button>
        </form>

        <p class="vault-text-center vault-text-secondary vault-signin-link">
          Already have an account?
          <a href="/sign-in" class="vault-link">Sign in</a>
        </p>

        <div v-if="socialButtonsPlacement === 'bottom' && hasOAuthProviders" class="vault-social-section">
          <div class="vault-divider">
            <span class="vault-divider-text">or</span>
          </div>
          <slot name="oauth-buttons" :providers="oauthProviders" :handle-o-auth="handleOAuth">
            <div class="vault-social-buttons">
              <button
                v-for="provider in oauthProviders"
                :key="provider"
                type="button"
                class="vault-btn vault-btn-social"
                :disabled="isLoading"
                @click="handleOAuth(provider)"
              >
                <span class="vault-social-icon">{{ getProviderIcon(provider) }}</span>
                <span>Continue with {{ capitalize(provider) }}</span>
              </button>
            </div>
          </slot>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed } from 'vue';
import { useSignUp } from '../composables';
import type { SignUpProps, ApiError } from '../types';

/**
 * Props definition with defaults
 */
const props = withDefaults(defineProps<SignUpProps>(), {
  oauthProviders: () => [],
  requireName: false,
});

/**
 * Emits definition
 */
const emit = defineEmits<{
  (e: 'success'): void;
  (e: 'error', error: ApiError): void;
}>();

/**
 * Local state
 */
const name = ref('');
const email = ref('');
const password = ref('');
const localError = ref<string | null>(null);

/**
 * Composables
 */
const { signUp, signUpWithOAuth, isLoading, error, resetError } = useSignUp();

/**
 * Computed
 */
const displayError = computed(() => localError.value || error.value?.message);
const hasOAuthProviders = computed(() => props.oauthProviders && props.oauthProviders.length > 0);
const socialButtonsPlacement = computed(() => props.appearance?.layout?.socialButtonsPlacement || 'top');
const isValid = computed(() => {
  if (props.requireName && !name.value.trim()) return false;
  if (!email.value.trim() || !email.value.includes('@')) return false;
  if (password.value.length < 8) return false;
  return true;
});

/**
 * Form submission handler
 */
async function handleSubmit() {
  resetError();
  localError.value = null;

  try {
    const signUpData: { email: string; password: string; name?: string } = {
      email: email.value,
      password: password.value,
    };

    if (props.requireName && name.value) {
      signUpData.name = name.value;
    }

    await signUp(signUpData);
    emit('success');
    if (props.redirectUrl) {
      window.location.href = props.redirectUrl;
    }
  } catch (err: any) {
    const errorMessage = err.message || 'Failed to create account';
    localError.value = errorMessage;
    emit('error', err as ApiError);
  }
}

/**
 * OAuth sign up handler
 */
async function handleOAuth(provider: 'google' | 'github' | 'microsoft') {
  resetError();
  localError.value = null;
  try {
    await signUpWithOAuth({ provider, redirectUrl: props.redirectUrl });
  } catch (err: any) {
    localError.value = err.message || 'Failed to sign up';
    emit('error', err as ApiError);
  }
}

/**
 * Get OAuth provider icon
 */
function getProviderIcon(provider: string): string {
  const icons: Record<string, string> = {
    google: '🔍',
    github: '🐙',
    microsoft: '🪟',
  };
  return icons[provider] || '🔑';
}

/**
 * Capitalize first letter
 */
function capitalize(str: string): string {
  return str.charAt(0).toUpperCase() + str.slice(1);
}
</script>

<style scoped>
.vault-sign-up {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
}

.vault-card {
  background: white;
  border-radius: 8px;
  box-shadow: 0 1px 3px rgba(0, 0, 0, 0.1);
  border: 1px solid #e5e7eb;
  max-width: 400px;
  width: 100%;
}

.vault-card-centered {
  margin: 0 auto;
}

.vault-card-header {
  padding: 1.5rem 1.5rem 0.5rem;
  text-align: center;
}

.vault-title {
  font-size: 1.5rem;
  font-weight: 600;
  color: #111827;
  margin: 0;
}

.vault-card-content {
  padding: 1rem 1.5rem 1.5rem;
}

.vault-form-group {
  margin-bottom: 1rem;
}

.vault-label {
  display: block;
  font-size: 0.875rem;
  font-weight: 500;
  color: #374151;
  margin-bottom: 0.25rem;
}

.vault-input {
  width: 100%;
  padding: 0.5rem 0.75rem;
  font-size: 0.875rem;
  line-height: 1.5;
  color: #111827;
  background-color: white;
  border: 1px solid #d1d5db;
  border-radius: 0.375rem;
  box-sizing: border-box;
  transition: border-color 0.15s ease-in-out, box-shadow 0.15s ease-in-out;
}

.vault-input:focus {
  outline: none;
  border-color: #3b82f6;
  box-shadow: 0 0 0 3px rgba(59, 130, 246, 0.1);
}

.vault-input:disabled {
  background-color: #f3f4f6;
  cursor: not-allowed;
}

.vault-hint {
  display: block;
  margin-top: 0.25rem;
  font-size: 0.75rem;
  color: #6b7280;
}

.vault-btn {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  gap: 0.5rem;
  padding: 0.5rem 1rem;
  font-size: 0.875rem;
  font-weight: 500;
  line-height: 1.5;
  text-align: center;
  white-space: nowrap;
  vertical-align: middle;
  cursor: pointer;
  user-select: none;
  border: 1px solid transparent;
  border-radius: 0.375rem;
  transition: all 0.15s ease-in-out;
  background: transparent;
}

.vault-btn:disabled {
  opacity: 0.6;
  cursor: not-allowed;
}

.vault-btn-primary {
  color: white;
  background-color: #0066cc;
  border-color: #0066cc;
}

.vault-btn-primary:hover:not(:disabled) {
  background-color: #0052a3;
  border-color: #0052a3;
}

.vault-btn-social {
  width: 100%;
  color: #374151;
  background-color: white;
  border-color: #d1d5db;
}

.vault-btn-social:hover:not(:disabled) {
  background-color: #f9fafb;
}

.vault-btn-full {
  width: 100%;
}

.vault-link {
  color: #0066cc;
  text-decoration: none;
}

.vault-link:hover {
  text-decoration: underline;
}

.vault-alert {
  padding: 0.75rem 1rem;
  border-radius: 0.375rem;
  font-size: 0.875rem;
}

.vault-alert-error {
  color: #991b1b;
  background-color: #fef2f2;
  border: 1px solid #fecaca;
}

.vault-divider {
  display: flex;
  align-items: center;
  margin: 1rem 0;
}

.vault-divider::before,
.vault-divider::after {
  content: '';
  flex: 1;
  border-top: 1px solid #e5e7eb;
}

.vault-divider-text {
  padding: 0 1rem;
  font-size: 0.75rem;
  color: #6b7280;
  text-transform: uppercase;
}

.vault-social-buttons {
  display: flex;
  flex-direction: column;
  gap: 0.5rem;
}

.vault-social-icon {
  font-size: 1.125rem;
}

.vault-text-center {
  text-align: center;
}

.vault-text-secondary {
  color: #6b7280;
}

.vault-signin-link {
  margin-top: 1rem;
  font-size: 0.875rem;
}

.vault-spinner {
  display: inline-block;
  border: 2px solid #e5e7eb;
  border-top-color: currentColor;
  border-radius: 50%;
  animation: vault-spin 1s linear infinite;
}

.vault-spinner-small {
  width: 1rem;
  height: 1rem;
}

.vault-spinner-inline {
  margin-right: 0.5rem;
}

@keyframes vault-spin {
  to {
    transform: rotate(360deg);
  }
}
</style>
