// packages/sdks/app-sdks/vue/src/components/WebAuthnButton.vue
<template>
  <button
    type="button"
    class="vault-webauthn-btn"
    :class="[
      `vault-webauthn-btn-${props.mode}`,
      props.class,
      { 'vault-webauthn-btn-loading': isLoading }
    ]"
    :disabled="isDisabled"
    @click="handleClick"
  >
    <span v-if="isLoading" class="vault-spinner vault-spinner-small vault-spinner-inline"></span>
    <span v-else class="vault-webauthn-icon">
      <svg v-if="props.mode === 'signin'" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
        <path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"/>
        <path d="m9 12 2 2 4-4"/>
      </svg>
      <svg v-else-if="props.mode === 'signup'" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
        <path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"/>
        <line x1="12" y1="8" x2="12" y2="16"/>
        <line x1="8" y1="12" x2="16" y2="12"/>
      </svg>
      <svg v-else xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
        <path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"/>
        <path d="M12 8v4"/>
        <path d="M12 16h.01"/>
      </svg>
    </span>
    <span class="vault-webauthn-label">{{ displayLabel }}</span>
  </button>
</template>

<script setup lang="ts">
import { computed } from 'vue';
import { useWebAuthn } from '../composables';
import type { WebAuthnButtonProps, ApiError } from '../types';

/**
 * Props definition with defaults
 */
const props = withDefaults(defineProps<WebAuthnButtonProps>(), {
  mode: 'signin',
});

/**
 * Emits definition
 */
const emit = defineEmits<{
  (e: 'success'): void;
  (e: 'error', error: ApiError): void;
}>();

/**
 * Composables
 */
const {
  isSupported,
  isLoading,
  error,
  register,
  authenticate,
  resetError,
} = useWebAuthn();

/**
 * Computed
 */
const isDisabled = computed(() => {
  return !isSupported.value || isLoading.value;
});

const displayLabel = computed(() => {
  if (props.label) return props.label;

  const labels: Record<string, string> = {
    signin: 'Sign in with Passkey',
    signup: 'Register Passkey',
    link: 'Link Passkey',
  };

  return labels[props.mode] || 'Passkey';
});

/**
 * Handle button click
 */
async function handleClick() {
  resetError();

  try {
    if (props.mode === 'signin') {
      await authenticate();
    } else if (props.mode === 'signup' || props.mode === 'link') {
      await register();
    }

    emit('success');
  } catch (err) {
    emit('error', err as ApiError);
  }
}
</script>

<style scoped>
.vault-webauthn-btn {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  gap: 0.5rem;
  padding: 0.625rem 1rem;
  font-size: 0.875rem;
  font-weight: 500;
  line-height: 1.5;
  text-align: center;
  white-space: nowrap;
  vertical-align: middle;
  cursor: pointer;
  user-select: none;
  border: 1px solid transparent;
  border-radius: 0.375rem;
  transition: all 0.15s ease-in-out;
  background: transparent;
}

.vault-webauthn-btn:disabled {
  opacity: 0.6;
  cursor: not-allowed;
}

.vault-webauthn-btn-signin {
  color: #374151;
  background-color: white;
  border-color: #d1d5db;
}

.vault-webauthn-btn-signin:hover:not(:disabled) {
  background-color: #f9fafb;
  border-color: #9ca3af;
}

.vault-webauthn-btn-signup {
  color: white;
  background-color: #0066cc;
  border-color: #0066cc;
}

.vault-webauthn-btn-signup:hover:not(:disabled) {
  background-color: #0052a3;
  border-color: #0052a3;
}

.vault-webauthn-btn-link {
  color: #0066cc;
  background-color: #eff6ff;
  border-color: #bfdbfe;
}

.vault-webauthn-btn-link:hover:not(:disabled) {
  background-color: #dbeafe;
  border-color: #93c5fd;
}

.vault-webauthn-icon {
  width: 1.25rem;
  height: 1.25rem;
  flex-shrink: 0;
}

.vault-webauthn-icon svg {
  width: 100%;
  height: 100%;
}

.vault-webauthn-label {
  flex: 1;
}

.vault-spinner {
  display: inline-block;
  border: 2px solid currentColor;
  border-top-color: transparent;
  border-radius: 50%;
  animation: vault-spin 1s linear infinite;
}

.vault-spinner-small {
  width: 1rem;
  height: 1rem;
}

.vault-spinner-inline {
  margin-right: 0.25rem;
}

@keyframes vault-spin {
  to {
    transform: rotate(360deg);
  }
}
</style>

// packages/sdks/app-sdks/svelte/src/lib/components/WebAuthnButton.svelte
<script lang="ts">
  /**
   * WebAuthnButton Component
   * 
   * Button for WebAuthn/passkey authentication.
   * 
   * @example
   * ```svelte
   * <WebAuthnButton 
   *   mode="signin"
   *   label="Sign in with passkey"
   *   onSuccess={() => console.log('Signed in!')}
   * />
   * ```
   */
  import { getVaultContext } from '../context.js';
  import type { WebAuthnButtonProps, ApiError, WebAuthnCredential } from '../types.js';
  
  let { 
    mode = 'signin',
    label,
    onSuccess,
    onError,
    className = ''
  }: WebAuthnButtonProps = $props();
  
  const vault = getVaultContext();
  
  let isLoading = $state(false);
  let error = $state<ApiError | null>(null);
  
  // Check if WebAuthn is supported
  const isSupported = typeof window !== 'undefined' && 
    typeof window.PublicKeyCredential !== 'undefined';
  
  async function handleClick() {
    if (!isSupported) {
      onError?.({ code: 'webauthn_not_supported', message: 'WebAuthn is not supported in this browser' });
      return;
    }
    
    isLoading = true;
    error = null;
    
    try {
      if (mode === 'signin' || mode === 'signup') {
        await authenticate();
      } else if (mode === 'link') {
        await register();
      }
      onSuccess?.();
    } catch (e) {
      error = e as ApiError;
      onError?.(error);
    } finally {
      isLoading = false;
    }
  }
  
  async function authenticate(): Promise<void> {
    // Begin authentication
    const options = await vault.api.beginWebAuthnAuthentication();
    
    // Convert challenge from base64url to ArrayBuffer
    const challenge = base64urlToBuffer(options.challenge);
    const allowCredentials = [];
    
    const credential = await navigator.credentials.get({
      publicKey: {
        ...options,
        challenge,
        allowCredentials,
      }
    }) as PublicKeyCredential;
    
    if (!credential) {
      throw new Error('No credential returned');
    }
    
    // Finish authentication
    await vault.api.finishWebAuthnAuthentication(serializeCredential(credential));
    
    // Update auth state
    await vault.reloadUser();
  }
  
  async function register(): Promise<void> {
    // Begin registration
    const options = await vault.api.beginWebAuthnRegistration();
    
    // Convert base64url strings to ArrayBuffers
    const challenge = base64urlToBuffer(options.challenge);
    const userId = base64urlToBuffer(options.user.id);
    
    const credential = await navigator.credentials.create({
      publicKey: {
        ...options,
        challenge,
        user: {
          ...options.user,
          id: userId,
        },
      }
    }) as PublicKeyCredential;
    
    if (!credential) {
      throw new Error('No credential created');
    }
    
    // Finish registration
    await vault.api.finishWebAuthnRegistration(serializeCredential(credential));
    
    // Update user
    await vault.reloadUser();
  }
  
  function base64urlToBuffer(base64url: string): ArrayBuffer {
    const base64 = base64url.replace(/-/g, '+').replace(/_/g, '/');
    const binary = atob(base64);
    const bytes = new Uint8Array(binary.length);
    for (let i = 0; i < binary.length; i++) {
      bytes[i] = binary.charCodeAt(i);
    }
    return bytes.buffer;
  }
  
  function bufferToBase64url(buffer: ArrayBuffer): string {
    const bytes = new Uint8Array(buffer);
    let binary = '';
    for (let i = 0; i < bytes.byteLength; i++) {
      binary += String.fromCharCode(bytes[i]);
    }
    return btoa(binary).replace(/\+/g, '-').replace(/\//g, '_').replace(/=/g, '');
  }
  
  function serializeCredential(credential: PublicKeyCredential): unknown {
    if (credential.response instanceof AuthenticatorAttestationResponse) {
      return {
        id: credential.id,
        rawId: bufferToBase64url(credential.rawId),
        type: credential.type,
        response: {
          clientDataJSON: bufferToBase64url(credential.response.clientDataJSON),
          attestationObject: bufferToBase64url(credential.response.attestationObject),
        }
      };
    } else {
      return {
        id: credential.id,
        rawId: bufferToBase64url(credential.rawId),
        type: credential.type,
        response: {
          clientDataJSON: bufferToBase64url(credential.response.clientDataJSON),
          authenticatorData: bufferToBase64url((credential.response as AuthenticatorAssertionResponse).authenticatorData),
          signature: bufferToBase64url((credential.response as AuthenticatorAssertionResponse).signature),
          userHandle: (credential.response as AuthenticatorAssertionResponse).userHandle 
            ? bufferToBase64url((credential.response as AuthenticatorAssertionResponse).userHandle!)
            : null,
        }
      };
    }
  }
  
  // Default labels based on mode
  const defaultLabel = {
    signin: 'Sign in with passkey',
    signup: 'Sign up with passkey',
    link: 'Add passkey'
  }[mode];
</script>

{#if isSupported}
  <button
    type="button"
    class="vault-webauthn-btn {className}"
    onclick={handleClick}
    disabled={isLoading}
  >
    <svg class="vault-webauthn-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
      <path d="M12 2a5 5 0 0 1 5 5v2a5 5 0 0 1-10 0V7a5 5 0 0 1 5-5z" />
      <path d="M12 14v8" />
      <path d="M9 18h6" />
      <path d="M8 22h8" />
    </svg>
    
    {#if isLoading}
      {#if mode === 'signin'}
        Verifying...
      {:else if mode === 'signup'}
        Setting up...
      {:else}
        Adding passkey...
      {/if}
    {:else}
      {label || defaultLabel}
    {/if}
  </button>
  
  {#if error}
    <p class="vault-webauthn-error">{error.message}</p>
  {/if}
{:else}
  <div class="vault-webauthn-unsupported">
    Passkeys are not supported in this browser
  </div>
{/if}

<style>
  .vault-webauthn-btn {
    display: flex;
    align-items: center;
    justify-content: center;
    gap: 0.5rem;
    width: 100%;
    padding: 0.625rem 1rem;
    background: white;
    border: 1px solid #e5e7eb;
    border-radius: 0.375rem;
    font-size: 0.875rem;
    font-weight: 500;
    color: #374151;
    cursor: pointer;
    transition: all 0.15s;
  }
  
  .vault-webauthn-btn:hover:not(:disabled) {
    background: #f9fafb;
    border-color: #d1d5db;
  }
  
  .vault-webauthn-btn:disabled {
    opacity: 0.5;
    cursor: not-allowed;
  }
  
  .vault-webauthn-icon {
    width: 1.25rem;
    height: 1.25rem;
  }
  
  .vault-webauthn-error {
    margin-top: 0.5rem;
    font-size: 0.875rem;
    color: #dc2626;
  }
  
  .vault-webauthn-unsupported {
    padding: 0.75rem;
    background: #f3f4f6;
    border-radius: 0.375rem;
    font-size: 0.875rem;
    color: #6b7280;
    text-align: center;
  }
</style>
