// packages/sdks/app-sdks/svelte/src/lib/components/WebAuthnButton.svelte
<script lang="ts">
  /**
   * WebAuthnButton Component
   * 
   * Button for WebAuthn/passkey authentication.
   * 
   * @example
   * ```svelte
   * <WebAuthnButton 
   *   mode="signin"
   *   label="Sign in with passkey"
   *   onSuccess={() => console.log('Signed in!')}
   * />
   * ```
   */
  import { getVaultContext } from '../context.js';
  import type { WebAuthnButtonProps, ApiError, WebAuthnCredential } from '../types.js';
  
  let { 
    mode = 'signin',
    label,
    onSuccess,
    onError,
    className = ''
  }: WebAuthnButtonProps = $props();
  
  const vault = getVaultContext();
  
  let isLoading = $state(false);
  let error = $state<ApiError | null>(null);
  
  // Check if WebAuthn is supported
  const isSupported = typeof window !== 'undefined' && 
    typeof window.PublicKeyCredential !== 'undefined';
  
  async function handleClick() {
    if (!isSupported) {
      onError?.({ code: 'webauthn_not_supported', message: 'WebAuthn is not supported in this browser' });
      return;
    }
    
    isLoading = true;
    error = null;
    
    try {
      if (mode === 'signin' || mode === 'signup') {
        await authenticate();
      } else if (mode === 'link') {
        await register();
      }
      onSuccess?.();
    } catch (e) {
      error = e as ApiError;
      onError?.(error);
    } finally {
      isLoading = false;
    }
  }
  
  async function authenticate(): Promise<void> {
    // Begin authentication
    const options = await vault.api.beginWebAuthnAuthentication();
    
    // Convert challenge from base64url to ArrayBuffer
    const challenge = base64urlToBuffer(options.challenge);
    const allowCredentials = [];
    
    const credential = await navigator.credentials.get({
      publicKey: {
        ...options,
        challenge,
        allowCredentials,
      }
    }) as PublicKeyCredential;
    
    if (!credential) {
      throw new Error('No credential returned');
    }
    
    // Finish authentication
    await vault.api.finishWebAuthnAuthentication(serializeCredential(credential));
    
    // Update auth state
    await vault.reloadUser();
  }
  
  async function register(): Promise<void> {
    // Begin registration
    const options = await vault.api.beginWebAuthnRegistration();
    
    // Convert base64url strings to ArrayBuffers
    const challenge = base64urlToBuffer(options.challenge);
    const userId = base64urlToBuffer(options.user.id);
    
    const credential = await navigator.credentials.create({
      publicKey: {
        ...options,
        challenge,
        user: {
          ...options.user,
          id: userId,
        },
      }
    }) as PublicKeyCredential;
    
    if (!credential) {
      throw new Error('No credential created');
    }
    
    // Finish registration
    await vault.api.finishWebAuthnRegistration(serializeCredential(credential));
    
    // Update user
    await vault.reloadUser();
  }
  
  function base64urlToBuffer(base64url: string): ArrayBuffer {
    const base64 = base64url.replace(/-/g, '+').replace(/_/g, '/');
    const binary = atob(base64);
    const bytes = new Uint8Array(binary.length);
    for (let i = 0; i < binary.length; i++) {
      bytes[i] = binary.charCodeAt(i);
    }
    return bytes.buffer;
  }
  
  function bufferToBase64url(buffer: ArrayBuffer): string {
    const bytes = new Uint8Array(buffer);
    let binary = '';
    for (let i = 0; i < bytes.byteLength; i++) {
      binary += String.fromCharCode(bytes[i]);
    }
    return btoa(binary).replace(/\+/g, '-').replace(/\//g, '_').replace(/=/g, '');
  }
  
  function serializeCredential(credential: PublicKeyCredential): unknown {
    if (credential.response instanceof AuthenticatorAttestationResponse) {
      return {
        id: credential.id,
        rawId: bufferToBase64url(credential.rawId),
        type: credential.type,
        response: {
          clientDataJSON: bufferToBase64url(credential.response.clientDataJSON),
          attestationObject: bufferToBase64url(credential.response.attestationObject),
        }
      };
    } else {
      return {
        id: credential.id,
        rawId: bufferToBase64url(credential.rawId),
        type: credential.type,
        response: {
          clientDataJSON: bufferToBase64url(credential.response.clientDataJSON),
          authenticatorData: bufferToBase64url((credential.response as AuthenticatorAssertionResponse).authenticatorData),
          signature: bufferToBase64url((credential.response as AuthenticatorAssertionResponse).signature),
          userHandle: (credential.response as AuthenticatorAssertionResponse).userHandle 
            ? bufferToBase64url((credential.response as AuthenticatorAssertionResponse).userHandle!)
            : null,
        }
      };
    }
  }
  
  // Default labels based on mode
  const defaultLabel = {
    signin: 'Sign in with passkey',
    signup: 'Sign up with passkey',
    link: 'Add passkey'
  }[mode];
</script>

{#if isSupported}
  <button
    type="button"
    class="vault-webauthn-btn {className}"
    onclick={handleClick}
    disabled={isLoading}
  >
    <svg class="vault-webauthn-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
      <path d="M12 2a5 5 0 0 1 5 5v2a5 5 0 0 1-10 0V7a5 5 0 0 1 5-5z" />
      <path d="M12 14v8" />
      <path d="M9 18h6" />
      <path d="M8 22h8" />
    </svg>
    
    {#if isLoading}
      {#if mode === 'signin'}
        Verifying...
      {:else if mode === 'signup'}
        Setting up...
      {:else}
        Adding passkey...
      {/if}
    {:else}
      {label || defaultLabel}
    {/if}
  </button>
  
  {#if error}
    <p class="vault-webauthn-error">{error.message}</p>
  {/if}
{:else}
  <div class="vault-webauthn-unsupported">
    Passkeys are not supported in this browser
  </div>
{/if}

<style>
  .vault-webauthn-btn {
    display: flex;
    align-items: center;
    justify-content: center;
    gap: 0.5rem;
    width: 100%;
    padding: 0.625rem 1rem;
    background: white;
    border: 1px solid #e5e7eb;
    border-radius: 0.375rem;
    font-size: 0.875rem;
    font-weight: 500;
    color: #374151;
    cursor: pointer;
    transition: all 0.15s;
  }
  
  .vault-webauthn-btn:hover:not(:disabled) {
    background: #f9fafb;
    border-color: #d1d5db;
  }
  
  .vault-webauthn-btn:disabled {
    opacity: 0.5;
    cursor: not-allowed;
  }
  
  .vault-webauthn-icon {
    width: 1.25rem;
    height: 1.25rem;
  }
  
  .vault-webauthn-error {
    margin-top: 0.5rem;
    font-size: 0.875rem;
    color: #dc2626;
  }
  
  .vault-webauthn-unsupported {
    padding: 0.75rem;
    background: #f3f4f6;
    border-radius: 0.375rem;
    font-size: 0.875rem;
    color: #6b7280;
    text-align: center;
  }
</style>

// packages/sdks/app-sdks/js/src/components/WebAuthnButton.tsx
/**
 * WebAuthnButton Component
 * 
 * Button for WebAuthn/Passkey authentication.
 * 
 * @example
 * ```tsx
 * // Sign in with passkey
 * <WebAuthnButton mode="signin" label="Sign in with Passkey" />
 * 
 * // Register new passkey
 * <WebAuthnButton mode="signup" label="Register Passkey" />
 * 
 * // Link passkey to existing account
 * <WebAuthnButton mode="link" label="Add Passkey" />
 * ```
 */

import React, { useState, useCallback } from 'react';
import { useWebAuthn } from '../hooks/useWebAuthn';
import { useVault } from '../context/VaultContext';
import { WebAuthnButtonProps, ApiError } from '../types';

export type { WebAuthnButtonProps };

export function WebAuthnButton({
  mode = 'signin',
  label,
  onSuccess,
  onError,
  appearance,
  className,
}: WebAuthnButtonProps) {
  const { isSupported, isLoading, error, register, authenticate, resetError } = useWebAuthn();
  const [localError, setLocalError] = useState<string | null>(null);
  const [showNameInput, setShowNameInput] = useState(false);
  const [passkeyName, setPasskeyName] = useState('');

  const handleClick = useCallback(async () => {
    resetError();
    setLocalError(null);

    if (!isSupported) {
      const err: ApiError = {
        code: 'webauthn_not_supported',
        message: 'Passkeys are not supported on this device',
      };
      setLocalError(err.message);
      onError?.(err);
      return;
    }

    try {
      if (mode === 'signup' || mode === 'link') {
        if (!showNameInput) {
          setShowNameInput(true);
          return;
        }
        await register(passkeyName || undefined);
        setShowNameInput(false);
        setPasskeyName('');
      } else {
        await authenticate();
      }
      onSuccess?.();
    } catch (err: any) {
      setLocalError(err.message || 'Passkey operation failed');
      onError?.(err as ApiError);
    }
  }, [mode, isSupported, register, authenticate, onSuccess, onError, resetError, showNameInput, passkeyName]);

  const handleCancel = useCallback(() => {
    setShowNameInput(false);
    setPasskeyName('');
  }, []);

  if (!isSupported) {
    return (
      <div style={applyAppearance(styles.unsupported, appearance)} className={className}>
        <span style={styles.unsupportedText}>
          Passkeys not supported on this device
        </span>
      </div>
    );
  }

  const displayError = localError || error?.message;

  // Get default label based on mode
  const getDefaultLabel = () => {
    switch (mode) {
      case 'signin':
        return 'Sign in with Passkey';
      case 'signup':
        return 'Register Passkey';
      case 'link':
        return 'Add Passkey';
      default:
        return 'Continue with Passkey';
    }
  };

  const buttonLabel = label || getDefaultLabel();

  if (showNameInput) {
    return (
      <div style={applyAppearance(styles.container, appearance)} className={className}>
        <div style={styles.inputGroup}>
          <input
            type="text"
            value={passkeyName}
            onChange={(e) => setPasskeyName(e.target.value)}
            placeholder="Name your passkey (optional)"
            style={applyAppearance(styles.input, appearance)}
            disabled={isLoading}
            autoFocus
          />
          <button
            onClick={handleClick}
            disabled={isLoading}
            style={applyAppearance(styles.button, appearance)}
          >
            {isLoading ? 'Registering...' : 'Register'}
          </button>
          <button
            onClick={handleCancel}
            disabled={isLoading}
            style={applyAppearance(styles.cancelButton, appearance)}
          >
            Cancel
          </button>
        </div>
        {displayError && (
          <div style={applyAppearance(styles.error, appearance)} role="alert">
            {displayError}
          </div>
        )}
      </div>
    );
  }

  return (
    <div style={applyAppearance(styles.container, appearance)} className={className}>
      <button
        onClick={handleClick}
        disabled={isLoading}
        style={applyAppearance(styles.button, appearance)}
      >
        <PasskeyIcon />
        <span>{isLoading ? 'Please wait...' : buttonLabel}</span>
      </button>
      {displayError && (
        <div style={applyAppearance(styles.error, appearance)} role="alert">
          {displayError}
        </div>
      )}
    </div>
  );
}

// Passkey Icon Component
function PasskeyIcon() {
  return (
    <svg
      width="20"
      height="20"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="8" r="4" />
      <path d="M12 12v8" />
      <path d="M9 16h6" />
      <path d="M8 20h8" />
      <rect x="4" y="2" width="16" height="20" rx="2" />
    </svg>
  );
}

// Apply appearance variables
function applyAppearance(
  baseStyle: React.CSSProperties,
  appearance?: { theme?: string; variables?: Record<string, string>; elements?: Record<string, React.CSSProperties> }
): React.CSSProperties {
  if (!appearance) return baseStyle;

  const variables = appearance.variables || {};
  let style = { ...baseStyle };

  if (variables['colorPrimary']) {
    if (baseStyle.backgroundColor === '#0066cc' || baseStyle.borderColor === '#0066cc') {
      style = { ...style, backgroundColor: variables['colorPrimary'], borderColor: variables['colorPrimary'] };
    }
  }

  if (variables['borderRadius'] && baseStyle.borderRadius) {
    style = { ...style, borderRadius: variables['borderRadius'] };
  }

  return style;
}

// Styles
const styles: Record<string, React.CSSProperties> = {
  container: {
    fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
  },
  button: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '8px',
    width: '100%',
    padding: '12px 16px',
    fontSize: '16px',
    fontWeight: 500,
    color: '#374151',
    backgroundColor: '#f3f4f6',
    border: '1px solid #d1d5db',
    borderRadius: '6px',
    cursor: 'pointer',
    transition: 'all 0.15s ease-in-out',
  },
  inputGroup: {
    display: 'flex',
    gap: '8px',
    marginBottom: '8px',
  },
  input: {
    flex: 1,
    padding: '10px 12px',
    fontSize: '15px',
    border: '1px solid #d1d5db',
    borderRadius: '6px',
    outline: 'none',
  },
  cancelButton: {
    padding: '10px 16px',
    fontSize: '14px',
    fontWeight: 500,
    color: '#6b7280',
    backgroundColor: '#f3f4f6',
    border: '1px solid #d1d5db',
    borderRadius: '6px',
    cursor: 'pointer',
  },
  error: {
    marginTop: '8px',
    padding: '8px 12px',
    fontSize: '13px',
    color: '#dc2626',
    backgroundColor: '#fee2e2',
    borderRadius: '6px',
  },
  unsupported: {
    padding: '12px',
    textAlign: 'center',
    backgroundColor: '#f3f4f6',
    borderRadius: '6px',
  },
  unsupportedText: {
    fontSize: '14px',
    color: '#6b7280',
  },
};
